openapi: 3.0.2
info:
  title: Jobs Internal
  version: "1.0"
servers:
  - url: https://localhost:3000/api
    description: Internal Api
security: []
paths:
  /{language}/jobs:
    get:
      operationId: getJobs
      summary: Get filtered and paginated jobs
      tags:
        - job
      parameters:
        - name: language
          in: path
          required: true
          style: simple
          explode: false
          schema:
            $ref: "#/components/schemas/Language"
      responses:
        "200":
          description: Filtered, paginated jobs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs_response"
        "400":
          description: Invalid query parameters
        "404":
          description: Language not found
components:
  schemas:
    Id:
      type: string
      example: "123"
    Address:
      type: object
      properties:
        street:
          type: string
          example: Wiener Str.
        city:
          type: string
          example: Bern
        canton:
          type: string
          example: Bern
        region:
          type: string
          example: Western Part of Switzerland
        country:
          type: string
          example: Switzerland
    DateTime:
      type: string
      format: date-time
    ActiveFilters:
      type: object
      properties:
        careerFields:
          $ref: "#/components/schemas/Tags"
        technologies:
          $ref: "#/components/schemas/Tags"
        industries:
          $ref: "#/components/schemas/Tags"
        jobLevels:
          $ref: "#/components/schemas/Tags"
        companySizes:
          $ref: "#/components/schemas/Tags"
        workload:
          $ref: "#/components/schemas/Range"
        homeOffice:
          type: number
          example: 70
        salary:
          type: number
        cantons:
          type: array
          example:
            - Baden
            - Lugano
          items:
            type: string
    Filters:
      type: object
      properties:
        careerFields:
          $ref: "#/components/schemas/Tags"
        technologies:
          $ref: "#/components/schemas/Tags"
        industries:
          $ref: "#/components/schemas/Tags"
        jobLevels:
          $ref: "#/components/schemas/Tags"
        companySizes:
          $ref: "#/components/schemas/Tags"
        workload:
          $ref: "#/components/schemas/Range"
        homeOffice:
          $ref: "#/components/schemas/Range"
        salary:
          $ref: "#/components/schemas/Range"
        cantons:
          type: array
          example:
            - Baden
            - Lugano
          items:
            type: string

    Metainfo:
      type: object
      properties:
        title:
          type: string
          example: "EN: Linux Systems Engineer"
        description:
          type: string
          example: "EN: Du möchtest Dein Knowhow bei einem führenden IaaS/PaaS-Dienstleister einbringen und vertiefen? Dann sollten wir uns kennenlernen."
        keywords:
          type: array
          items:
            type: string
          example:
            - "Excel"
            - "Virtualisation"
            - "VMware EN"
        authors:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "Vlada Berozkina | digitalent ag"
        openGraph:
          type: object
          properties:
            title:
              type: string
              example: "EN: Linux Systems Engineer"
            description:
              type: string
              example: "EN: Du möchtest Dein Knowhow bei einem führenden IaaS/PaaS-Dienstleister einbringen und vertiefen? Dann sollten wir uns kennenlernen."
            url:
              type: string
              format: url
              example: "https://karriere.aspectra.ch/en/linux-systems-engineer"
            images:
              type: array
              items:
                type: object
                properties:
                  url:
                    type: string
                    format: url
                    example: "https://karriere.aspectra.ch/media/3613/aspectra-linux-systems-engineer.jpg"
                  width:
                    type: number
                    example: 1200
                  height:
                    type: number
                    example: 630
                  alt:
                    type: string
                    example: "EN: Linux Systems Engineer"
                required:
                  - url
            locale:
              type: string
              example: "ch_en"
            type:
              type: string
              enum:
                - website
                - article
                - book
                - profile
                - music.song
                - music.album
                - music.playlist
                - music.radio_station
                - video.movie
                - video.episode
                - video.tv_show
                - video.other
              example: "website"
        twitter:
          type: object
          properties:
            card:
              type: string
              enum:
                - summary
                - summary_large_image
                - player
                - app
              example: "summary_large_image"
            title:
              type: string
              example: "EN: Linux Systems Engineer"
            description:
              type: string
              example: "EN: Du möchtest Dein Knowhow bei einem führenden IaaS/PaaS-Dienstleister einbringen und vertiefen? Dann sollten wir uns kennenlernen."
            creator:
              type: string
              example: "Vlada Berozkina | digitalent ag"
            images:
              type: array
              items:
                type: string
                format: url
                example: "https://karriere.aspectra.ch/media/3613/aspectra-linux-systems-engineer.jpg"
    Tags:
      type: array
      example:
        - tag1
        - tag2
        - tag3
      items:
        type: string
    File:
      type: object
      properties:
        content:
          type: string
          format: base64
          example: "data:image/webp;base64,UklGRs61AABXRUJQVlA4WAoAAA"
        lastModified:
          type: number
        name:
          type: string
          example: cv.webp
        size:
          type: number
        type:
          type: string
          example: image/webp
    SalaryRange:
      type: object
      properties:
        amount:
          $ref: "#/components/schemas/Range"
        currency:
          type: string
        unit:
          type: string
      example:
        amount:
          - 40000
          - 100000
        currency: CHF
        unit: year
    Employer:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        name:
          type: string
          example: Baggenstos
        logo:
          type: string
          format: url
    Range:
      maxLength: 2
      minLength: 2
      type: array
      example:
        - 20
        - 80
      items:
        type: number
    Language:
      maxLength: 2
      type: string
      default: de
      enum:
        - de
        - en
        - fr
    Job:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
        title:
          type: string
          example: React Engineer
        datePosted:
          $ref: "#/components/schemas/DateTime"
        address:
          $ref: "#/components/schemas/Address"
        employer:
          $ref: "#/components/schemas/Employer"
        salary:
          $ref: "#/components/schemas/SalaryRange"
        workload:
          $ref: "#/components/schemas/Range"
        homeOffice:
          $ref: "#/components/schemas/Range"
        tags:
          $ref: "#/components/schemas/Tags"
        technologies:
          $ref: "#/components/schemas/Tags"
        jobLevel:
          type: string
        companySize:
          type: string
        landingPageUrl:
          type: string
          format: url
        responsibilities:
          type: string
          format: markup
        requirements:
          type: string
          format: markup
        metainfo:
          $ref: "#/components/schemas/Metainfo"
    jobs_response:
      type: object
      properties:
        jobs:
          type: array
          items:
            $ref: "#/components/schemas/Job"
        length:
          type: integer
          description: "Length of the collection of jobs"
    subscribe_body:
      type: object
      properties:
        email:
          type: string
          format: email
        activeFilters:
          $ref: "#/components/schemas/ActiveFilters"
    save_body:
      type: object
      properties:
        email:
          type: string
          format: email
        jobId:
          type: string
    apply_body:
      type: object
      properties:
        email:
          type: string
          format: email
        sex:
          type: string
          enum:
            - man
            - woman
            - other
        name:
          type: string
        message:
          type: string
        files:
          type: array
          items:
            $ref: "#/components/schemas/File"
        linkedIn:
          type: string
          format: url
        jobIds:
          type: array
          items:
            $ref: "#/components/schemas/Id"
    refer_body:
      type: object
      properties:
        email:
          type: string
          format: email
        jobId:
          $ref: "#/components/schemas/Id"
  parameters:
    UserId:
      name: userId
      in: query
      required: false
      style: form
      explode: true
      schema:
        $ref: "#/components/schemas/Id"
    BoardId:
      name: boardId
      in: query
      required: false
      style: form
      explode: true
      schema:
        $ref: "#/components/schemas/Id"
    Language:
      name: language
      in: path
      required: true
      style: simple
      explode: false
      schema:
        $ref: "#/components/schemas/Language"
    Offset:
      name: offset
      in: query
      description: "For pagination: index of the first job to be sent"
      required: false
      style: form
      explode: true
      schema:
        type: number
    Limit:
      name: limit
        in: query
        description: "For pagination: limit of jobs to be sent"
        required: false
        style: form
        explode: true
        schema:
          type: number
    ActiveFiltersQueryParams:
      - name: careerFields
        in: query
        required: false
        style: form
        explode: false
        schema:
          $ref: "#/components/schemas/Tags"
        example:
          - frontend
          - fullstack
      - name: technologies
        in: query
        required: false
        style: form
        explode: false
        schema:
          $ref: "#/components/schemas/Tags"
        example:
          - react
          - nodejs
      - name: industries
        in: query
        required: false
        style: form
        explode: false
        schema:
          $ref: "#/components/schemas/Tags"
        example:
          - it
      - name: jobLevels
        in: query
        required: false
        style: form
        explode: false
        schema:
          $ref: "#/components/schemas/Tags"
        example:
          - contributor
          - expert
          - leader
      - name: companySizes
        in: query
        required: false
        style: form
        explode: false
        schema:
          $ref: "#/components/schemas/Tags"
        example:
          - StartUp
      - name: workload
        in: query
        required: false
        style: form
        explode: false
        schema:
          $ref: "#/components/schemas/Range"
        example:
          - 80
          - 100
      - name: homeOffice
        in: query
        required: false
        style: form
        explode: false
        schema:
          type: number
        example: 70
      - name: cantons
        in: query
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
          - Baden
          - Lugano
      - name: salary
        in: query
        required: false
        style: form
        explode: false
        schema:
          type: number
        example: 80000