import "../globals.css";
import { Inter } from "next/font/google";
import { i18n } from "../../../i18n-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  params,
  children,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={params?.locale || "de"}>
      <body className={inter.className}>
        <h1 className="text-white text-3xl">LOCALE: {params.locale}</h1>
        {children}
      </body>
    </html>
  );
}
